Compile fix for renamed classes.
QMake utilized a cached version of asmprogramlisting when compiling.
This hid an error caused by an undefined reference to the old UI classes.